#!/usr/bin/env bash
# Keeps always-apply skill invariants present in the workspace.
#
#   session    materialize the invariants into an instructions file, report what is armed
#   post-tool  after a file edit, restate the invariant covering that path (observe only)
#   emit       print the invariant block to stdout (for hosts that add hook stdout to context)
#
# Never blocks: every path exits 0.

set -uo pipefail

MODE="${1:-session}"
HOOK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG="${ALWAYS_ON_CONFIG:-$HOOK_DIR/always-on-skills.json}"

if ! command -v jq >/dev/null 2>&1; then
  echo "always-on-skills: 'jq' is required but not installed - skipping." >&2
  exit 0
fi

if [ ! -f "$CONFIG" ]; then
  echo "always-on-skills: no config at $CONFIG - skipping." >&2
  exit 0
fi

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || cd "$HOOK_DIR/../../.." && pwd)"
INSTRUCTIONS_PATH="$REPO_ROOT/$(jq -r '.instructionsPath // ".github/instructions/always-on-skills.instructions.md"' "$CONFIG")"
LOG_PATH="$REPO_ROOT/$(jq -r '.logPath // ".github/logs/always-on-skills.log"' "$CONFIG")"

# Enabled skills, one per line: name<TAB>invariant
enabled_skills() {
  jq -r '.skills[] | select((.enabled // true) == true) | [.name, .invariant] | @tsv' "$CONFIG"
}

render_block() {
  printf '%s\n' "These skills apply to every response in this workspace. They do not lapse when the topic changes."
  printf '\n'
  while IFS=$'\t' read -r name invariant; do
    [ -z "$name" ] && continue
    printf -- '## %s\n\n%s\n\n' "$name" "$invariant"
  done < <(enabled_skills)
  printf '%s\n' "If one of these conflicts with a task instruction, the task wins and the invariant still applies to how the result is reported."
}

case "$MODE" in
  session)
    count="$(enabled_skills | grep -c . || true)"
    if [ "$count" -eq 0 ]; then
      echo "always-on-skills: no skills enabled in $(basename "$CONFIG") - nothing armed." >&2
      exit 0
    fi

    mkdir -p "$(dirname "$INSTRUCTIONS_PATH")" 2>/dev/null || true
    tmp="$(mktemp 2>/dev/null || echo "${INSTRUCTIONS_PATH}.tmp")"
    {
      printf -- '---\n'
      printf "description: 'Always-apply quality invariants for this workspace. Generated by the always-on-skills hook - edit always-on-skills.json, not this file.'\n"
      printf "applyTo: '**'\n"
      printf -- '---\n\n'
      printf -- '<!-- GENERATED FILE - do not edit. Source: .github/hooks/always-on-skills/always-on-skills.json -->\n\n'
      printf -- '# Always-Apply Skills\n\n'
      render_block
    } > "$tmp"

    if [ -f "$INSTRUCTIONS_PATH" ] && cmp -s "$tmp" "$INSTRUCTIONS_PATH"; then
      rm -f "$tmp"
      echo "always-on-skills: $count skill(s) armed, instructions file already current." >&2
    else
      mv -f "$tmp" "$INSTRUCTIONS_PATH" 2>/dev/null || cp -f "$tmp" "$INSTRUCTIONS_PATH"
      echo "always-on-skills: $count skill(s) armed, wrote $(basename "$INSTRUCTIONS_PATH")." >&2
    fi
    enabled_skills | cut -f1 | sed 's/^/  - /' >&2
    ;;

  post-tool)
    payload="$(cat 2>/dev/null || true)"
    [ -z "$payload" ] && exit 0

    tool_name="$(printf '%s' "$payload" | jq -r '.toolName // ""' 2>/dev/null)"
    case "$tool_name" in
      edit | create | str_replace_editor | write | multi_edit) ;;
      *) exit 0 ;;
    esac

    tool_args="$(printf '%s' "$payload" | jq -r '.toolArgs // "{}"' 2>/dev/null)"
    path="$(printf '%s' "$tool_args" | jq -r '.path // .filePath // .file_path // ""' 2>/dev/null)"
    [ -z "$path" ] && exit 0
    # Normalize separators on both sides before stripping: hosts report either form.
    rel="${path//\\//}"
    root_slash="${REPO_ROOT//\\//}"
    rel="${rel#"$root_slash/"}"

    matched=0
    while IFS=$'\t' read -r name invariant; do
      [ -z "$name" ] && continue
      patterns="$(jq -r --arg n "$name" '.skills[] | select(.name == $n) | (.appliesTo // ["*"])[]' "$CONFIG")"
      # A skill scoped to everything is already carried by the instructions file.
      # Per-edit reminders are for path-scoped skills only, or every edit gets every invariant.
      [ "$(printf '%s' "$patterns" | tr -d '[:space:]')" = "*" ] && continue
      while IFS= read -r pat; do
        [ -z "$pat" ] && continue
        # shellcheck disable=SC2053
        if [[ "$rel" == $pat ]]; then
          echo "always-on-skills: $rel is in scope of '$name'." >&2
          echo "  $invariant" >&2
          matched=1
          break
        fi
      done <<< "$patterns"
    done < <(enabled_skills)

    if [ "$matched" -eq 1 ]; then
      mkdir -p "$(dirname "$LOG_PATH")" 2>/dev/null || true
      printf '%s\t%s\t%s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$tool_name" "$rel" >> "$LOG_PATH" 2>/dev/null || true
    fi
    ;;

  emit)
    render_block
    ;;

  *)
    echo "always-on-skills: unknown mode '$MODE' (expected session, post-tool, or emit)." >&2
    ;;
esac

exit 0
