# Keeps always-apply skill invariants present in the workspace.
#
#   -Mode session    materialize the invariants into an instructions file, report what is armed
#   -Mode post-tool  after a file edit, restate the invariant covering that path (observe only)
#   -Mode emit       print the invariant block to stdout (for hosts that add hook stdout to context)
#
# Never blocks: every path exits 0.

param(
  [ValidateSet('session', 'post-tool', 'emit')]
  [string]$Mode = 'session'
)

$ErrorActionPreference = 'Continue'

$hookDir = Split-Path -Parent $PSScriptRoot
$configPath = if ($env:ALWAYS_ON_CONFIG) { $env:ALWAYS_ON_CONFIG } else { Join-Path $hookDir 'always-on-skills.json' }

if (-not (Test-Path $configPath)) {
  [Console]::Error.WriteLine("always-on-skills: no config at $configPath - skipping.")
  exit 0
}

try {
  $config = Get-Content -Raw -LiteralPath $configPath | ConvertFrom-Json
}
catch {
  [Console]::Error.WriteLine("always-on-skills: config at $configPath is not valid JSON - skipping.")
  exit 0
}

$repoRoot = (& git rev-parse --show-toplevel 2>$null)
if (-not $repoRoot) { $repoRoot = (Resolve-Path (Join-Path $hookDir '..\..\..')).Path }
$repoRoot = $repoRoot.Trim().Replace('/', [System.IO.Path]::DirectorySeparatorChar)

$instructionsRel = if ($config.instructionsPath) { $config.instructionsPath } else { '.github/instructions/always-on-skills.instructions.md' }
$logRel = if ($config.logPath) { $config.logPath } else { '.github/logs/always-on-skills.log' }
$instructionsPath = Join-Path $repoRoot $instructionsRel
$logPath = Join-Path $repoRoot $logRel

$enabled = @($config.skills | Where-Object { $null -eq $_.enabled -or $_.enabled -eq $true })

function Get-InvariantBlock {
  $lines = @(
    'These skills apply to every response in this workspace. They do not lapse when the topic changes.',
    ''
  )
  foreach ($skill in $enabled) {
    $lines += "## $($skill.name)"
    $lines += ''
    $lines += $skill.invariant
    $lines += ''
  }
  $lines += 'If one of these conflicts with a task instruction, the task wins and the invariant still applies to how the result is reported.'
  return ($lines -join "`n")
}

switch ($Mode) {
  'session' {
    if ($enabled.Count -eq 0) {
      [Console]::Error.WriteLine('always-on-skills: no skills enabled - nothing armed.')
      exit 0
    }

    $header = @(
      '---',
      "description: 'Always-apply quality invariants for this workspace. Generated by the always-on-skills hook - edit always-on-skills.json, not this file.'",
      "applyTo: '**'",
      '---',
      '',
      '<!-- GENERATED FILE - do not edit. Source: .github/hooks/always-on-skills/always-on-skills.json -->',
      '',
      '# Always-Apply Skills',
      ''
    ) -join "`n"

    $content = $header + "`n" + (Get-InvariantBlock) + "`n"
    $dir = Split-Path -Parent $instructionsPath
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }

    $current = if (Test-Path $instructionsPath) { Get-Content -Raw -LiteralPath $instructionsPath } else { $null }
    if ($current -eq $content) {
      [Console]::Error.WriteLine("always-on-skills: $($enabled.Count) skill(s) armed, instructions file already current.")
    }
    else {
      Set-Content -LiteralPath $instructionsPath -Value $content -NoNewline -Encoding utf8
      [Console]::Error.WriteLine("always-on-skills: $($enabled.Count) skill(s) armed, wrote $(Split-Path -Leaf $instructionsPath).")
    }
    foreach ($skill in $enabled) { [Console]::Error.WriteLine("  - $($skill.name)") }
  }

  'post-tool' {
    $raw = [Console]::In.ReadToEnd()
    if ([string]::IsNullOrWhiteSpace($raw)) { exit 0 }

    try { $payload = $raw | ConvertFrom-Json } catch { exit 0 }
    if ($payload.toolName -notin @('edit', 'create', 'str_replace_editor', 'write', 'multi_edit')) { exit 0 }

    try { $toolArgs = $payload.toolArgs | ConvertFrom-Json } catch { $toolArgs = $payload.toolArgs }
    $path = $toolArgs.path
    if (-not $path) { $path = $toolArgs.filePath }
    if (-not $path) { $path = $toolArgs.file_path }
    if (-not $path) { exit 0 }

    # Normalize separators on both sides before stripping: hosts report either form.
    $rel = $path.Replace('\', '/')
    $rootSlash = $repoRoot.Replace('\', '/')
    if ($rel.StartsWith($rootSlash, [System.StringComparison]::OrdinalIgnoreCase)) {
      $rel = $rel.Substring($rootSlash.Length)
    }
    $rel = $rel.TrimStart('/')

    $matched = $false
    foreach ($skill in $enabled) {
      $patterns = @(if ($skill.appliesTo) { $skill.appliesTo } else { @('*') })
      # A skill scoped to everything is already carried by the instructions file.
      # Per-edit reminders are for path-scoped skills only, or every edit gets every invariant.
      if ($patterns.Count -eq 1 -and $patterns[0].Trim() -eq '*') { continue }
      foreach ($pattern in $patterns) {
        if ($rel -like $pattern) {
          [Console]::Error.WriteLine("always-on-skills: $rel is in scope of '$($skill.name)'.")
          [Console]::Error.WriteLine("  $($skill.invariant)")
          $matched = $true
          break
        }
      }
    }

    if ($matched) {
      $logDir = Split-Path -Parent $logPath
      if (-not (Test-Path $logDir)) { New-Item -ItemType Directory -Force -Path $logDir | Out-Null }
      $stamp = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
      Add-Content -LiteralPath $logPath -Value "$stamp`t$($payload.toolName)`t$rel"
    }
  }

  'emit' {
    Write-Output (Get-InvariantBlock)
  }
}

exit 0
